server:
  port: 0
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    client:
      exchange: ${RABBITMQ_EXCHANGE}
      routing: ${RABBITMQ_ROUTING}
  application:
    name: odeme-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}

fpos:
  servis:
    url: ${FPOS_URL}
spos:
  servis:
    url: ${SPOS_URL}
nakit:
  servis:
    url: ${NAKIT_URL}

springdoc:
  packagesToScan: tr.gov.gib.odeme
  cache:
    disabled: true
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1


management:
  tracing:
    sampling:
      probability: 1.0
#
#swagger:
#  info:
#    title: ${SWAGGER_TITLE}
#    version: ${SWAGGER_VERSION}
#    description: ${SWAGGER_DSC}
#    termsOfService: ${SWAGGER_TOS}
#    contact:
#      name: ${SWAGGER_NAME}
#      email: ${SWAGGER_EMAIL}